### ISSUE TITLE
Add Device: W541

### ISSUE THREAD

**Issue by Thrilleratplay** [Thrilleratplay/coreboot-builder-scripts#17]
I have a W541 currently running coreboot 4.15 and Tianocore.  I need to stream line the process for `mrc.bin`

* Create SeaBIOS build
* Add unit tests

**Comment by gellatofresh** [comment]
Dead ?

**Comment by Thrilleratplay** [comment]
@gellatofresh I need to make a few updates but I am using Tianocore on my W541.  I have not tested SeaBIOS

**Comment by gellatofresh** [comment]
That is great. 
I'm curious what the notable issues are currently. 
Have you users it with the 1620p display?

**Comment by Thrilleratplay** [comment]
@gellatofresh I pushed the latest rendition of the W541 Tianocore build into the `W541_tianocore` branch.  The custom boot image does not work but everything else should be fine.

**Comment by gellatofresh** [comment]
Thanks much man. Let me see what I can do to contribute. Should have some time soon.

**Comment by Thrilleratplay** [comment]
Currently am waiting for the next `coreboot-sdk` release, which should include the needed programs to extract the `mrc.bin` automatically.

**Comment by Thrilleratplay** [comment]
@gellatofresh I finally had some time to finish and test this.  It has been merged into the `seabios` and  `edk2` branches.  Sorry for the delay.
